apiVersion: v2
name: monitoring
description: Prometheus + Grafana stack for game-project
type: application

# версия самого чарта (меняешь при изменениях чарта)
version: 0.1.0

# версия приложения (просто информативно)
appVersion: "1.0.0"