targetNamespace: game-services-staging

source:
  namespace: observability
  secretName: local-secret-store

store:
  name: local-secret-store

services:
  apiGateway:
    enabled: true
    targetSecretName: secret-api-gateway
    data:
      AUTH_SERVICE_URL: AUTH_SERVICE_URL
      CATALOG_SERVICE_URL: CATALOG_SERVICE_URL
      USER_SERVICE_URL: USER_SERVICE_URL
      FRONTEND_URL: FRONTEND_URL
      FRONTEND_URLS: FRONTEND_URLS
      JWT_ACCESS_SECRET: JWT_ACCESS_SECRET
      JWT_REFRESH_SECRET: JWT_REFRESH_SECRET
      PORT: PORT

  auth:
    enabled: true
    targetSecretName: secret-auth-service
    data:
      DATABASE_URL: DATABASE_URL
      REDIS_URL: REDIS_URL
      NODE_ENV: NODE_ENV
      JWT_ACCESS_SECRET: JWT_ACCESS_SECRET
      JWT_REFRESH_SECRET: JWT_REFRESH_SECRET
      SMTP_HOST: SMTP_HOST
      SMTP_PORT: SMTP_PORT
      SMTP_USER: SMTP_USER
      SMTP_PASS: SMTP_PASS
      EMAIL_FROM: EMAIL_FROM
      EMAIL_CONFIRM_TTL_MINUTES: EMAIL_CONFIRM_TTL_MINUTES
      PASSWORD_RESET_TTL_MINUTES: PASSWORD_RESET_TTL_MINUTES
      FRONTEND_URL: FRONTEND_URL
      FRONTEND_URLS: FRONTEND_URLS
      GATEWAY_PUBLIC_URL: GATEWAY_PUBLIC_URL
      PORT: PORT

  catalog:
    enabled: true
    targetSecretName: secret-catalog-service
    data:
      DATABASE_URL: DATABASE_URL
      PORT: PORT

  user:
    enabled: true
    targetSecretName: secret-user-service
    data:
      DATABASE_URL: DATABASE_URL
      REDIS_URL: REDIS_URL
      PORT: PORT