{{- if .Values.services.user.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-user-service
  namespace: {{ .Values.targetNamespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.store.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.services.user.targetSecretName }}
    creationPolicy: Owner
  data:
  {{- range $targetKey, $sourceKey := .Values.services.user.data }}
    - secretKey: {{ $targetKey }}
      remoteRef:
        key: {{ $.Values.source.secretName }}
        property: {{ $sourceKey }}
  {{- end }}
{{- end }}