apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-local-secret-store-access
rules:
  # читать source secret в observability
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  # писать target secrets в namespaces
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-local-secret-store-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-local-secret-store-access
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets