apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.store.name }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.source.namespace }}
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets