{{- if .Values.authService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-service-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: auth-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.authService.ingress.host }}
      http:
        paths:
          - path: {{ .Values.authService.ingress.path }}
            pathType: {{ .Values.authService.ingress.pathType }}
            backend:
              service:
                name: auth-service
                port:
                  number: {{ .Values.authService.service.port }}
{{- end }}