apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: game-project-staging
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: game-project-staging
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io