apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}{{- if .Values.image.digest }}@{{ .Values.image.digest }}{{- else }}:{{ .Values.image.tag }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}

          # ✅ Забираем ВСЕ переменные из Kubernetes Secret
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.envSecretName | default "secret-user" | quote }}

          resources:
{{ toYaml .Values.resources | indent 12 }}