{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: user-service-sa
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.userService.containerPort }}

          envFrom:
            - secretRef:
                name: user-service-secrets

          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.userService.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.userService.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.userService.resources.requests.cpu | quote }}
              memory: {{ .Values.userService.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.userService.resources.limits.cpu | quote }}
              memory: {{ .Values.userService.resources.limits.memory | quote }}
{{- end }}