{{- if and .Values.userService.enabled .Values.userService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: user-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.userService.ingress.host }}
      http:
        paths:
          - path: {{ .Values.userService.ingress.path }}
            pathType: {{ .Values.userService.ingress.pathType }}
            backend:
              service:
                name: user-service
                port:
                  number: {{ .Values.userService.service.port }}
{{- end }}