backend:
  image:

    repository: arnold2343/game-backend
    tag: "1.0.0"          # дефолтный тег, можно переопределять в values.local.yaml / values.prod.yaml
    pullPolicy: IfNotPresent

  replicaCount: 1
  containerPort: 3000

  service:
    port: 3000
  migrations:
    enabled: false

  # Только НЕсекретные значения
  env:
    MONGO_URI: "mongodb://mongo:27017/game-db"
    REDIS_URL: "redis://redis:6379"

    # Для Postgres — только host/port/name/user, без пароля
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    POSTGRES_DB: "game_db"
    POSTGRES_USER: "game_user"

  # Какой Secret использовать для backend-а
  secretName: backend-secrets

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  ingress:
    enabled: true
    host: api.game.local
    path: /api
    pathType: Prefix

mongo:
  image: mongo:6
  port: 27017

redis:
  image: redis:7
  port: 6379

monitoring:
  prometheus:
    enabled: false
    image: prom/prometheus:latest
    service:
      port: 9090

  grafana:
    enabled: false
    image: grafana/grafana:latest
    service:
      port: 3000

    adminUser: admin
    adminPassword: admin

    loki:
      enabled: false
      image: grafana/loki:2.9.0
      service:
        port: 3100

    promtail:
      enabled: false
      image: grafana/promtail:2.9.0

postgres:
  enabled: true

  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent

  # Без пароля — он будет только в Secret
  auth:
    username: "game_user"
    database: "game_db"

  # Имя секрета с реальными значениями
  secretName: postgres-secret

  persistence:
    size: 5Gi
