backend:
  image:
    repository: arnold2343/game-backend
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    port: 3000

  env:
    MONGO_URI: "mongodb://mongo:27017/game-db"
    REDIS_URL: "redis://redis:6379"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  ingress:
    enabled: true
    host: game.localhost
    path: /api
    pathType: Prefix

mongo:
  image: mongo:6
  port: 27017

redis:
  image: redis:7
  port: 6379

monitoring:
  prometheus:
    enabled: false
    image: prom/prometheus:latest
    service:
      port: 9090

  grafana:
    enabled: false
    image: grafana/grafana:latest
    service:
      port: 3000

    adminUser: admin
    adminPassword: admin

    loki:
      enabled: false
      image: grafana/loki:2.9.0
      service:
        port: 3100

    promtail:
      enabled: false
      image: grafana/promtail:2.9.0