backend:
  image:
    tag: "1b0733f36aab8184c3b217f82e05741b66c76bc9"  # твой локальный/актуальный тег

  # Если хочешь — можешь локально переопределять env
  env:
    MONGO_URI: "mongodb://mongo:27017/game-db"
    REDIS_URL: "redis://redis:6379"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    POSTGRES_DB: "game_db"
    POSTGRES_USER: "game_user"

postgres:
  # Можно переопределить только несекретные поля (если нужно)
  auth:
    username: "game_user"
    database: "game_db"