apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: main
    path: k8s/charts/services/api-gateway
    helm:
      valueFiles:
        - ../../../environments/staging/values/services/api-gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: game-services-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true