apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: main
    path: k8s/charts/platform/external-secrets/secrets
    helm:
      valueFiles:
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: game-services-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true