apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: main
    path: k8s/charts/platform/monitoring-stack
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: Prometheus
      jsonPointers: ["/status"]
    - group: monitoring.coreos.com
      kind: Alertmanager
      jsonPointers: ["/status"]
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jsonPointers: ["/status"]
    - group: monitoring.coreos.com
      kind: PodMonitor
      jsonPointers: ["/status"]
    - group: monitoring.coreos.com
      kind: PrometheusRule
      jsonPointers: ["/status"]
    - group: ""
      kind: Endpoints
      jqPathExpressions: [".subsets"]