# k8s/charts/platform/monitoring-stack/values.yaml

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 12h
      scrapeInterval: 30s

  grafana:
    enabled: true
    defaultDashboardsEnabled: true

  # если node-exporter идет как часть kube-prometheus-stack
  prometheus-node-exporter:
    enabled: false

# если node-exporter идет отдельной зависимостью (у тебя похоже именно так)
prometheus-node-exporter:
  enabled: false

tempo:
  enabled: true
  persistence:
    enabled: false

loki:
  enabled: false