kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 12h
      scrapeInterval: 30s

  grafana:
    enabled: true
    defaultDashboardsEnabled: true

  # ✅ FIX for Docker Desktop (Mac): disable node-exporter (hostPath "/" mount breaks)
  prometheus-node-exporter:
    enabled: false

tempo:
  enabled: true
  persistence:
    enabled: false

# ⛔ Loki тут не используется, пока нет зависимости loki в Chart.yaml
# loki:
#   enabled: false