name: auth-service | PR checks

on:
  pull_request:
    branches: ["main"]
    paths:
      - "auth-service/**"
      - ".github/workflows/pr/auth-service.pr.yml"
      - ".github/workflows/_lib/node-pr-checks.yml"

permissions:
  contents: read

concurrency:
  group: pr-auth-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_lib/node-pr-checks.yml
    with:
      service_name: "auth-service"
      working_directory: "auth-service"
      node_version: "20"
      cache_dependency_path: "auth-service/package-lock.json"
      run_lint: true
      run_test: true
      run_build: false