apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-from-ingress
  namespace: game-project
spec:
  podSelector:
    matchLabels:
      app: backend       # целимся в backend-поды
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx   # только pod'ы из ingress-nginx
      ports:
        - protocol: TCP
          port: 3000               # порт backend'а внутри pod'а