{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: game-project
  annotations:
    # Если будешь использовать nginx-ingress:
    # kubernetes.io/ingress.class: nginx
spec:
  # Если в кластере настроен ingressClass, можно указать:
  # ingressClassName: nginx
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: {{ .Values.backend.ingress.path }}
            pathType: {{ .Values.backend.ingress.pathType }}
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}