apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}{{- if .Values.image.digest }}@{{ .Values.image.digest }}{{- else }}:{{ .Values.image.tag }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}

          # ✅ Забираем ВСЕ переменные из Kubernetes Secret
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.envSecretName | default "secret-auth" | quote }}

          # (опционально) Можно оставить NODE_ENV, но он будет перекрывать значение из secret, если там тоже есть NODE_ENV
          env:
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"

          resources:
{{ toYaml .Values.resources | indent 12 }}