name: api-gateway | PR checks

on:
  pull_request:
    branches: ["main"]
    paths:
      - "api-gateway/**"
      - ".github/workflows/pr/api-gateway.pr.yml"
      - ".github/workflows/_lib/node-pr-checks.yml"

permissions:
  contents: read

concurrency:
  group: pr-api-gateway-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_lib-node-pr-checks.yml
    with:
      service_name: "api-gateway"
      working_directory: "api-gateway"
      node_version: "20"
      cache_dependency_path: "api-gateway/package-lock.json"
      run_lint: true
      run_test: true
      run_build: false