name: auth-service CI-CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "auth-service/**"
      - "k8s/game-project/**"
      - ".github/workflows/auth-service-ci.yml"

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: auth-service/package-lock.json

      - name: Install deps
        working-directory: auth-service
        run: npm ci

      - name: Lint
        working-directory: auth-service
        run: npm run lint

      - name: Test
        working-directory: auth-service
        run: npm test

  build-and-push:
    if: github.event_name == 'push' &&
        github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            arnold2343/game-backend:latest
            arnold2343/game-backend:${{ github.sha }}

  update-image-tag:
    if: github.event_name == 'push' &&
        github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-push

    env:
      IMAGE_TAG: ${{ github.sha }}
      VALUES_FILE: k8s/game-project/values-game-project-staging.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update authService image tag
        run: |
          yq -i '.authService.image.tag = strenv(IMAGE_TAG)' "$VALUES_FILE"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$VALUES_FILE"
          git commit -m "chore: update authService image tag to ${IMAGE_TAG} [skip ci]"
          git push origin main