name: catalog-service CI-CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "catalog-service/**"
      - ".github/workflows/catalog-service-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "catalog-service/**"

jobs:
  build-and-push:
    # только push в main и без [skip ci]
    if: github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push CATALOG image
        uses: docker/build-push-action@v6
        with:
          context: ./catalog-service
          file: ./catalog-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            arnold2343/game-catalog:latest
            arnold2343/game-catalog:${{ github.sha }}