name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-and-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: |
            backend/package-lock.json
            client/package-lock.json

      # ===== BACKEND =====
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint

      - name: Test backend (pass even if no tests)
        working-directory: backend
        run: npm test -- --passWithNoTests

      # ===== FRONTEND (build JS-бандла) =====
      - name: Install client deps
        working-directory: client
        run: npm install

      - name: Build frontend
        working-directory: client
        run: npm run build

      # ===============================
      #         DOCKER BUILD & PUSH
      # ===============================

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # должен быть arnold2343
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # QEMU нужен, чтобы собирать образы под amd64 + arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ----- BACKEND IMAGE -----
      - name: Build and push BACKEND Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./backend              # где лежит Dockerfile бекенда
          file: ./backend/Dockerfile      # путь к Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            arnold2343/game-backend:latest
            arnold2343/game-backend:${{ github.sha }}

      # ----- FRONTEND IMAGE -----
      - name: Build and push FRONTEND Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./client               # папка фронта
          file: ./client/Dockerfile       # путь к Dockerfile фронта
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            arnold2343/game-frontend:latest
            arnold2343/game-frontend:${{ github.sha }}